_target_: swagger_client.models.AlignmentTarget
id: qol-synth-HighCluster
kdma_values:
- kdes:
    globalnorm:
      kde: 'gASVhAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsMSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDYAAAAAAAAPA/

        AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D/////////nP////////+c/AAAAAAAA8D8A

        AAAAAADwP////////+c/AAAAAAAA8D8AAAAAAADwP5R0lGJoHWggSwCFlGgih5RSlChLAUsMhZRo

        J4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQ2AAAAAAAAAAAAEAAAAAAAAAAgAA

        AAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAAAGAAAAAAAAAAcAAAAAAAAACAAAAAAAAAAJAAAA

        AAAAAAoAAAAAAAAACwAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQoSwFLAYWUaCeMA1YzMpSJiIeU

        UpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19sZWFmlIwGcmFkaXVzlHSUfZQo

        aEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJLAIaUaEJoSUsIhpRoQ2hJSxCG

        lGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAADAAAAAAAAAABAAAAAAAAAAIAAAAAAMA/lHSU

        YmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsBh5RoKolDEP///////+c/AAAAAAAA8D+UdJRiSyhLAUsB

        SwBLAEsASwCMHXNrbGVhcm4ubWV0cmljcy5fZGlzdF9tZXRyaWNzlGgVk5RoWIwTRXVjbGlkZWFu

        RGlzdGFuY2U2NJSTlIWUUpRHQAAAAAAAAABoHWggSwCFlGgih5RSlChLAUsBhZRoKolDCAAAAAAA

        AAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwFLAYaUaCqJQwgAAAAAAAAAAJR0lGKHlGJOdJRijBBf

        c2tsZWFybl92ZXJzaW9ulIwFMS41LjGUdWIu

        '
      label: globalnorm
    globalnormx_localnormy:
      kde: 'gASV9AQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwKMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsMSwKGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDwAAAAAAAAPA/

        AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8A

        AAAAAADwPwAAAAAAAPA/////////5z/////////nP////////+c/////////5z8AAAAAAADwPwAA

        AAAAAPA/AAAAAAAA8D8AAAAAAADwP////////+c/////////5z8AAAAAAADwPwAAAAAAAPA/AAAA

        AAAA8D8AAAAAAADwP5R0lGJoHWggSwCFlGgih5RSlChLAUsMhZRoJ4wCaTiUiYiHlFKUKEsDaCtO

        Tk5K/////0r/////SwB0lGKJQ2AAAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAADAAAAAAAAAAQAAAAA

        AAAABQAAAAAAAAAGAAAAAAAAAAcAAAAAAAAACAAAAAAAAAAJAAAAAAAAAAoAAAAAAAAACwAAAAAA

        AACUdJRiaB1oIEsAhZRoIoeUUpQoSwFLAYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyUTiiMCWlkeF9z

        dGFydJSMB2lkeF9lbmSUjAdpc19sZWFmlIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiUiYiHlFKUKEsD

        aCtOTk5K/////0r/////SwB0lGJLAIaUaEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaUdUsgSwFLEHSU

        YolDIAAAAAAAAAAADAAAAAAAAAABAAAAAAAAAM87f2aeoMY/lHSUYmgdaCBLAIWUaCKHlFKUKEsB

        SwJLAUsCh5RoKolDIP///////+c/////////5z8AAAAAAADwPwAAAAAAAPA/lHSUYksoSwFLAUsA

        SwBLAEsAjB1za2xlYXJuLm1ldHJpY3MuX2Rpc3RfbWV0cmljc5RoFZOUaFiME0V1Y2xpZGVhbkRp

        c3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAAaB1oIEsAhZRoIoeUUpQoSwFLAYWUaCqJQwgAAAAAAAAA

        AJR0lGJoHWggSwCFlGgih5RSlChLAUsBSwGGlGgqiUMIAAAAAAAAAACUdJRih5RiTnSUYowQX3Nr

        bGVhcm5fdmVyc2lvbpSMBTEuNS4xlHViLg==

        '
      label: globalnormx_localnormy
    localnorm:
      kde: 'gASVhAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsMSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDYAAAAAAAAPA/

        AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D/////////nP////////+c/AAAAAAAA8D8A

        AAAAAADwP////////+c/AAAAAAAA8D8AAAAAAADwP5R0lGJoHWggSwCFlGgih5RSlChLAUsMhZRo

        J4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQ2AAAAAAAAAAAAEAAAAAAAAAAgAA

        AAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAAAGAAAAAAAAAAcAAAAAAAAACAAAAAAAAAAJAAAA

        AAAAAAoAAAAAAAAACwAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQoSwFLAYWUaCeMA1YzMpSJiIeU

        UpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19sZWFmlIwGcmFkaXVzlHSUfZQo

        aEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJLAIaUaEJoSUsIhpRoQ2hJSxCG

        lGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAADAAAAAAAAAABAAAAAAAAAAIAAAAAAMA/lHSU

        YmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsBh5RoKolDEP///////+c/AAAAAAAA8D+UdJRiSyhLAUsB

        SwBLAEsASwCMHXNrbGVhcm4ubWV0cmljcy5fZGlzdF9tZXRyaWNzlGgVk5RoWIwTRXVjbGlkZWFu

        RGlzdGFuY2U2NJSTlIWUUpRHQAAAAAAAAABoHWggSwCFlGgih5RSlChLAUsBhZRoKolDCAAAAAAA

        AAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwFLAYaUaCqJQwgAAAAAAAAAAJR0lGKHlGJOdJRijBBf

        c2tsZWFybl92ZXJzaW9ulIwFMS41LjGUdWIu

        '
      label: localnorm
    rawscores:
      kde: 'gASVhAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsMSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDYM3MzMzMzOw/

        zczMzMzM7D/NzMzMzMzsP83MzMzMzOw/zczMzMzM7D9mZmZmZmbmP2ZmZmZmZuY/zczMzMzM7D/N

        zMzMzMzsP2ZmZmZmZuY/zczMzMzM7D/NzMzMzMzsP5R0lGJoHWggSwCFlGgih5RSlChLAUsMhZRo

        J4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGKJQ2AAAAAAAAAAAAEAAAAAAAAAAgAA

        AAAAAAADAAAAAAAAAAQAAAAAAAAABQAAAAAAAAAGAAAAAAAAAAcAAAAAAAAACAAAAAAAAAAJAAAA

        AAAAAAoAAAAAAAAACwAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQoSwFLAYWUaCeMA1YzMpSJiIeU

        UpQoSwOMAXyUTiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19sZWFmlIwGcmFkaXVzlHSUfZQo

        aEFoJ4wCaTiUiYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJLAIaUaEJoSUsIhpRoQ2hJSxCG

        lGhEaCpLGIaUdUsgSwFLEHSUYolDIAAAAAAAAAAADAAAAAAAAAABAAAAAAAAAJyZmZmZmbk/lHSU

        YmgdaCBLAIWUaCKHlFKUKEsBSwJLAUsBh5RoKolDEGZmZmZmZuY/zczMzMzM7D+UdJRiSyhLAUsB

        SwBLAEsASwCMHXNrbGVhcm4ubWV0cmljcy5fZGlzdF9tZXRyaWNzlGgVk5RoWIwTRXVjbGlkZWFu

        RGlzdGFuY2U2NJSTlIWUUpRHQAAAAAAAAABoHWggSwCFlGgih5RSlChLAUsBhZRoKolDCAAAAAAA

        AAAAlHSUYmgdaCBLAIWUaCKHlFKUKEsBSwFLAYaUaCqJQwgAAAAAAAAAAJR0lGKHlGJOdJRijBBf

        c2tsZWFybl92ZXJzaW9ulIwFMS41LjGUdWIu

        '
      label: rawscores
  kdma: QualityOfLife
