_target_: swagger_client.models.AlignmentTarget
id: VOL_CS_cbca2c86833e
kdma_values:
- kdes:
    globalnorm:
      kde: 'gASVZAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsKSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDUAAAAAAAAPA/

        AAAAAAAAAAD////////nPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwP////////88/AAAAAAAAAAAA

        AAAAAADwPwAAAAAAAPA/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwqFlGgnjAJpOJSJiIeUUpQoSwNo

        K05OTkr/////Sv////9LAHSUYolDUAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAA

        AAAAAAAFAAAAAAAAAAYAAAAAAAAABwAAAAAAAAAIAAAAAAAAAAkAAAAAAAAAlHSUYmgdaCBLAIWU

        aCKHlFKUKEsBSwGFlGgnjANWMzKUiYiHlFKUKEsDjAF8lE4ojAlpZHhfc3RhcnSUjAdpZHhfZW5k

        lIwHaXNfbGVhZpSMBnJhZGl1c5R0lH2UKGhBaCeMAmk4lImIh5RSlChLA2grTk5OSv////9K////

        /0sAdJRiSwCGlGhCaElLCIaUaENoSUsQhpRoRGgqSxiGlHVLIEsBSxB0lGKJQyAAAAAAAAAAAAoA

        AAAAAAAAAQAAAAAAAAAAAAAAAADgP5R0lGJoHWggSwCFlGgih5RSlChLAUsCSwFLAYeUaCqJQxAA

        AAAAAAAAAAAAAAAAAPA/lHSUYksoSwFLAUsASwBLAEsAjB1za2xlYXJuLm1ldHJpY3MuX2Rpc3Rf

        bWV0cmljc5RoFZOUaFiME0V1Y2xpZGVhbkRpc3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAAaB1oIEsA

        hZRoIoeUUpQoSwFLAYWUaCqJQwgAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBSwGGlGgq

        iUMIAAAAAAAAAACUdJRih5RiTnSUYowQX3NrbGVhcm5fdmVyc2lvbpSMBTEuNS4xlHViLg==

        '
      label: globalnorm
    globalnormx_localnormy:
      kde: 'gASVxAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwKMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsKSwKGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDoAAAAAAAAPA/

        AAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAA////////5z/////////nPwAAAAAAAPA/AAAAAAAA8D8A

        AAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwP////////88/////////zz8AAAAAAAAAAAAA

        AAAAAAAAAAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D+UdJRiaB1oIEsAhZRoIoeUUpQo

        SwFLCoWUaCeMAmk4lImIh5RSlChLA2grTk5OSv////9K/////0sAdJRiiUNQAAAAAAAAAAABAAAA

        AAAAAAIAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAAUAAAAAAAAABgAAAAAAAAAHAAAAAAAAAAgAAAAA

        AAAACQAAAAAAAACUdJRiaB1oIEsAhZRoIoeUUpQoSwFLAYWUaCeMA1YzMpSJiIeUUpQoSwOMAXyU

        TiiMCWlkeF9zdGFydJSMB2lkeF9lbmSUjAdpc19sZWFmlIwGcmFkaXVzlHSUfZQoaEFoJ4wCaTiU

        iYiHlFKUKEsDaCtOTk5K/////0r/////SwB0lGJLAIaUaEJoSUsIhpRoQ2hJSxCGlGhEaCpLGIaU

        dUsgSwFLEHSUYolDIAAAAAAAAAAACgAAAAAAAAABAAAAAAAAAM07f2aeoOY/lHSUYmgdaCBLAIWU

        aCKHlFKUKEsBSwJLAUsCh5RoKolDIAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwPwAAAAAAAPA/lHSU

        YksoSwFLAUsASwBLAEsAjB1za2xlYXJuLm1ldHJpY3MuX2Rpc3RfbWV0cmljc5RoFZOUaFiME0V1

        Y2xpZGVhbkRpc3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAAaB1oIEsAhZRoIoeUUpQoSwFLAYWUaCqJ

        QwgAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBSwGGlGgqiUMIAAAAAAAAAACUdJRih5Ri

        TnSUYowQX3NrbGVhcm5fdmVyc2lvbpSMBTEuNS4xlHViLg==

        '
      label: globalnormx_localnormy
    localnorm:
      kde: 'gASVZAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsKSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDUAAAAAAAAPA/

        AAAAAAAAAAD////////nPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwP////////88/AAAAAAAAAAAA

        AAAAAADwPwAAAAAAAPA/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwqFlGgnjAJpOJSJiIeUUpQoSwNo

        K05OTkr/////Sv////9LAHSUYolDUAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAA

        AAAAAAAFAAAAAAAAAAYAAAAAAAAABwAAAAAAAAAIAAAAAAAAAAkAAAAAAAAAlHSUYmgdaCBLAIWU

        aCKHlFKUKEsBSwGFlGgnjANWMzKUiYiHlFKUKEsDjAF8lE4ojAlpZHhfc3RhcnSUjAdpZHhfZW5k

        lIwHaXNfbGVhZpSMBnJhZGl1c5R0lH2UKGhBaCeMAmk4lImIh5RSlChLA2grTk5OSv////9K////

        /0sAdJRiSwCGlGhCaElLCIaUaENoSUsQhpRoRGgqSxiGlHVLIEsBSxB0lGKJQyAAAAAAAAAAAAoA

        AAAAAAAAAQAAAAAAAAAAAAAAAADgP5R0lGJoHWggSwCFlGgih5RSlChLAUsCSwFLAYeUaCqJQxAA

        AAAAAAAAAAAAAAAAAPA/lHSUYksoSwFLAUsASwBLAEsAjB1za2xlYXJuLm1ldHJpY3MuX2Rpc3Rf

        bWV0cmljc5RoFZOUaFiME0V1Y2xpZGVhbkRpc3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAAaB1oIEsA

        hZRoIoeUUpQoSwFLAYWUaCqJQwgAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBSwGGlGgq

        iUMIAAAAAAAAAACUdJRih5RiTnSUYowQX3NrbGVhcm5fdmVyc2lvbpSMBTEuNS4xlHViLg==

        '
      label: localnorm
    rawscores:
      kde: 'gASVZAQAAAAAAACMFnNrbGVhcm4ubmVpZ2hib3JzLl9rZGWUjA1LZXJuZWxEZW5zaXR5lJOUKYGU

        fZQojAlhbGdvcml0aG2UjARhdXRvlIwJYmFuZHdpZHRolEc/szMzMzMzNIwGa2VybmVslIwIZ2F1

        c3NpYW6UjAZtZXRyaWOUjAlldWNsaWRlYW6UjARhdG9slEsAjARydG9slEsAjA1icmVhZHRoX2Zp

        cnN0lIiMCWxlYWZfc2l6ZZRLKIwNbWV0cmljX3BhcmFtc5ROjApiYW5kd2lkdGhflEc/szMzMzMz

        NIwObl9mZWF0dXJlc19pbl+USwGMBXRyZWVflIwac2tsZWFybi5uZWlnaGJvcnMuX2tkX3RyZWWU

        jAZuZXdPYmqUk5RoFIwGS0RUcmVllJOUhZRSlCiMFm51bXB5Ll9jb3JlLm11bHRpYXJyYXmUjAxf

        cmVjb25zdHJ1Y3SUk5SMBW51bXB5lIwHbmRhcnJheZSTlEsAhZRDAWKUh5RSlChLAUsKSwGGlGge

        jAVkdHlwZZSTlIwCZjiUiYiHlFKUKEsDjAE8lE5OTkr/////Sv////9LAHSUYolDUM3MzMzMzOw/

        mpmZmZmZuT9mZmZmZmbmP83MzMzMzOw/zczMzMzM7D/NzMzMzMzsPzMzMzMzM9M/mpmZmZmZuT/N

        zMzMzMzsP83MzMzMzOw/lHSUYmgdaCBLAIWUaCKHlFKUKEsBSwqFlGgnjAJpOJSJiIeUUpQoSwNo

        K05OTkr/////Sv////9LAHSUYolDUAAAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAMAAAAAAAAABAAA

        AAAAAAAFAAAAAAAAAAYAAAAAAAAABwAAAAAAAAAIAAAAAAAAAAkAAAAAAAAAlHSUYmgdaCBLAIWU

        aCKHlFKUKEsBSwGFlGgnjANWMzKUiYiHlFKUKEsDjAF8lE4ojAlpZHhfc3RhcnSUjAdpZHhfZW5k

        lIwHaXNfbGVhZpSMBnJhZGl1c5R0lH2UKGhBaCeMAmk4lImIh5RSlChLA2grTk5OSv////9K////

        /0sAdJRiSwCGlGhCaElLCIaUaENoSUsQhpRoRGgqSxiGlHVLIEsBSxB0lGKJQyAAAAAAAAAAAAoA

        AAAAAAAAAQAAAAAAAACamZmZmZnZP5R0lGJoHWggSwCFlGgih5RSlChLAUsCSwFLAYeUaCqJQxCa

        mZmZmZm5P83MzMzMzOw/lHSUYksoSwFLAUsASwBLAEsAjB1za2xlYXJuLm1ldHJpY3MuX2Rpc3Rf

        bWV0cmljc5RoFZOUaFiME0V1Y2xpZGVhbkRpc3RhbmNlNjSUk5SFlFKUR0AAAAAAAAAAaB1oIEsA

        hZRoIoeUUpQoSwFLAYWUaCqJQwgAAAAAAAAAAJR0lGJoHWggSwCFlGgih5RSlChLAUsBSwGGlGgq

        iUMIAAAAAAAAAACUdJRih5RiTnSUYowQX3NrbGVhcm5fdmVyc2lvbpSMBTEuNS4xlHViLg==

        '
      label: rawscores
  kdma: PerceivedQuantityOfLivesSaved
